field: a9304c4f-5334-4567-869a-fd00f4d3de14 # Post Content
fieldLayouts:
  f616c41e-5cb5-41b3-b10f-fd0f6267c868:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f008f5fa-5ee3-4d4b-8bdf-850df9cbdfdb # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e3913d41-dcd3-4d73-b389-b34a9868db22
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 93797c8d-d349-4ebe-944d-629ad5592c77
        userCondition: null
fields:
  f008f5fa-5ee3-4d4b-8bdf-850df9cbdfdb: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: true
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:41b50b20-73f7-4f03-9486-dd81eff990b3' # Uploads
      defaultUploadLocationSubpath: 'blog/{date.slug}'
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: '{date}'
      restrictedLocationSource: 'volume:41b50b20-73f7-4f03-9486-dd81eff990b3' # Uploads
      restrictedLocationSubpath: '@web/assets/blog'
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Add an image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: Image
sortOrder: 2
