columnSuffix: null
contentColumnType: string
fieldGroup: 50f0b566-40db-423d-bd76-e324969c46b0 # Blog Post Fields
handle: featureImage
instructions: null
name: 'Feature Image'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: true
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:41b50b20-73f7-4f03-9486-dd81eff990b3' # Uploads
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maxRelations: null
  minRelations: 1
  previewMode: full
  restrictFiles: true
  restrictLocation: true
  restrictedDefaultUploadSubpath: 'blog/{date}'
  restrictedLocationSource: 'volume:41b50b20-73f7-4f03-9486-dd81eff990b3' # Uploads
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: null
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
