columnSuffix: null
contentColumnType: string
fieldGroup: 50f0b566-40db-423d-bd76-e324969c46b0 # Blog Post Fields
handle: postContent
instructions: null
name: 'Post Content'
searchable: true
settings:
  contentTable: '{{%matrixcontent_postcontent}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
