fieldLayouts:
  d6d28a32-adea-4719-ac86-d670d3facefc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6b7ed5fd-678c-4e0e-858f-d05bd205215a # Site Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a132ab8e-d621-4346-abc5-a87a2dbdb984
            userCondition: null
            warning: null
            width: 100
        name: 'Site Info'
        uid: a44a0c23-31f4-49f9-9129-b7cefb4e6778
        userCondition: null
handle: siteInformation
name: 'Site Information'
sortOrder: 1
