defaultPlacement: end
enableVersioning: true
handle: about
name: About
propagationMethod: all
siteSettings:
  28180187-0148-487b-be94-5e438348a74b: # dearmaam
    enabledByDefault: true
    hasUrls: true
    template: _singles/about
    uriFormat: about
type: single
